"""Cross-result analysis: produce findings.md with per-(model, category) A→B deltas.

Merges OSS + Claude scored results, computes flag rates and deltas, classifies
each (model, category) cell as categorical / strong / marginal / null / negative,
and writes a markdown summary.

Run:
  python tests/abtests/analyze.py \
    --inputs tests/abtests/results/oss-run.scored-mech.jsonl tests/abtests/results/claude-run.scored-mech.jsonl \
    --judge tests/abtests/results/oss-run.scored-judge.jsonl tests/abtests/results/claude-run.scored-judge.jsonl \
    --out tests/abtests/findings.md
"""
from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path


CATEGORIES = [
    "refuse-vs-compute",
    "stale-vs-live",
    "cached-vs-recheck",
    "pre-computed-gap",
    "static-vs-versioned",
    "control",
]


def load_jsonl(path: Path) -> list[dict]:
    rows = []
    if not path.is_file():
        return rows
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def flag_rate(rows: list[dict], field: str = "mech_score") -> float:
    """flagged + 0.5 * partial, normalized by total non-error."""
    counts = Counter(r.get(field, "missed") for r in rows if "error" not in r)
    total = sum(counts.values())
    if total == 0:
        return 0.0
    return (counts.get("flagged", 0) + 0.5 * counts.get("partial", 0)) / total


def classify(delta: float, b_rate: float, a_rate: float) -> str:
    if b_rate >= 0.8 and a_rate <= 0.2:
        return "**CATEGORICAL**"
    if delta >= 0.5:
        return "strong"
    if delta >= 0.1:
        return "marginal"
    if abs(delta) < 0.1:
        return "null"
    return "negative"


def aggregate(rows: list[dict]) -> dict:
    """Group by (model, category, condition) and compute flag rates."""
    by_key: dict[tuple, list] = defaultdict(list)
    for r in rows:
        if "error" in r:
            continue
        key = (r.get("model"), r.get("category"), r.get("condition"))
        by_key[key].append(r)
    return by_key


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inputs", nargs="+", required=True, type=Path,
                    help="Mechanically-scored JSONL files")
    ap.add_argument("--judge", nargs="*", type=Path, default=[],
                    help="Judge-scored JSONL files (optional)")
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    # Load mechanical-scored rows
    all_rows = []
    for p in args.inputs:
        all_rows.extend(load_jsonl(p))
    print(f"Loaded {len(all_rows)} rows from {len(args.inputs)} input files")

    # Load judge scores keyed by (model, prompt_id, seed)
    judge_lookup: dict[tuple, str] = {}
    for p in args.judge:
        for r in load_jsonl(p):
            key = (r.get("model"), r.get("prompt_id"), r.get("seed"))
            judge_lookup[key] = r.get("judge_score", "?")
    print(f"Loaded {len(judge_lookup)} judge verdicts")

    by_key = aggregate(all_rows)

    # Per (model, category): rates for A, B, A2 (where present)
    model_cat_rates: dict[tuple, dict] = defaultdict(dict)
    for (model, cat, cond), rs in by_key.items():
        model_cat_rates[(model, cat)][cond] = {
            "flag_rate": flag_rate(rs),
            "n": len(rs),
        }

    # Build findings.md
    lines = []
    lines.append("# A/B test findings: AsOf temporal-awareness skill\n")
    lines.append("Generated by `tests/abtests/analyze.py`.\n")
    lines.append("## Method\n")
    lines.append("- 11 prompts across 5 effect-types + controls (battery.jsonl).")
    lines.append("- For each (model × prompt × condition × seed): one Ollama or Claude CLI call.")
    lines.append("- Mechanical scoring: regex keyword sets per category (see `rubric.md`). `flag_rate = (flagged + 0.5*partial) / total`.")
    lines.append("- LLM-judge (Claude Opus) cross-check on A/B pairs.")
    lines.append("- Classification: `CATEGORICAL` if B ≥ 0.8 and A ≤ 0.2; otherwise `strong` (delta ≥ 0.5), `marginal` (≥ 0.1), `null` (|delta| < 0.1), `negative` (delta < -0.1).\n")

    # Models in deterministic order: OSS first, then Claude tiers
    model_order = sorted({k[0] for k in model_cat_rates})

    lines.append("## Per-(model, category) results\n")
    lines.append("Each cell shows `A → B` flag rates and the delta. **CATEGORICAL** = the effect is clean and large.\n")

    for model in model_order:
        lines.append(f"### {model}\n")
        lines.append("| Category | A | B | Δ | Class | A2 |")
        lines.append("|---|---|---|---|---|---|")
        for cat in CATEGORIES:
            ratings = model_cat_rates.get((model, cat), {})
            a = ratings.get("A", {}).get("flag_rate", None)
            b = ratings.get("B", {}).get("flag_rate", None)
            a2 = ratings.get("A2", {}).get("flag_rate", None)
            if a is None or b is None:
                lines.append(f"| {cat} | — | — | — | (no data) | {a2:.2f if a2 is not None else '—'} |")
                continue
            delta = b - a
            cls = classify(delta, b, a)
            a2_str = f"{a2:.2f}" if a2 is not None else "—"
            lines.append(f"| {cat} | {a:.2f} | {b:.2f} | {delta:+.2f} | {cls} | {a2_str} |")
        lines.append("")

    # Summary of categorical effects
    categoricals = []
    strongs = []
    for (model, cat), ratings in sorted(model_cat_rates.items()):
        if cat == "control":
            continue
        a = ratings.get("A", {}).get("flag_rate", None)
        b = ratings.get("B", {}).get("flag_rate", None)
        if a is None or b is None:
            continue
        cls = classify(b - a, b, a)
        if "CATEGORICAL" in cls:
            categoricals.append((model, cat, a, b))
        elif cls == "strong":
            strongs.append((model, cat, a, b))

    lines.append("## Summary of categorical / strong effects\n")
    if categoricals:
        lines.append("**Categorical** (B ≥ 80% AND A ≤ 20%):")
        for m, c, a, b in categoricals:
            lines.append(f"- `{m}` × `{c}`: {a:.0%} → {b:.0%}")
        lines.append("")
    if strongs:
        lines.append("**Strong** (Δ ≥ 50% but not categorical):")
        for m, c, a, b in strongs:
            lines.append(f"- `{m}` × `{c}`: {a:.0%} → {b:.0%}")
        lines.append("")

    # Control sanity check
    lines.append("## Controls (should show null)\n")
    for model in model_order:
        ratings = model_cat_rates.get((model, "control"), {})
        a = ratings.get("A", {}).get("flag_rate", "—")
        b = ratings.get("B", {}).get("flag_rate", "—")
        lines.append(f"- `{model}`: A={a:.2f if a != '—' else '—'}, B={b:.2f if b != '—' else '—'}")
    lines.append("")

    # Cell count footer
    lines.append("## Cell counts\n")
    lines.append("| Model | Total cells | Errors |")
    lines.append("|---|---|---|")
    for model in model_order:
        total = sum(len(rs) for k, rs in by_key.items() if k[0] == model)
        errors = sum(1 for r in all_rows if r.get("model") == model and "error" in r)
        lines.append(f"| {model} | {total} | {errors} |")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
